pipeline-base: &pipeline_source_base
  source:
    connection-ref: "MYSQL1"
    query: |-
      SELECT * FROM table WHERE ID > :id_seq

pipelines:
  ingestion:
    "[PIPELINE_1]":
      enabled: true
      description: "Description"
      <<: *pipeline_source_base
      staging:
        collection-name: "ingestion-pipeline-1"
